### RECUPERAR INFORMACION DEL POKEMON DITTO
GET http://localhost:1234/pokemon/ditto
### PARA CREAR UN POKEMON
POST http://localhost:1234/pokemon
Content-Type: application/json

{
    "name":"ditto",
    "type":"normal",
    "moves":[
        "transform"
    ]
}